# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sms', '0001_initial'),
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_name', models.CharField(max_length=7, unique=True)),
                ('message', models.CharField(max_length=120)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='chain.Chain')),
            ],
            options={
                'ordering': ('expiry_date',),
            },
        ),
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='sms.SMS')),
            ],
        ),
    ]
