# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '0002_auto_20170703_1245'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('coupon_code', models.CharField(max_length=7, unique=True)),
                ('message', models.CharField(max_length=120)),
                ('unique_code', models.CharField(max_length=8)),
                ('publish_date', models.DateField(auto_now_add=True)),
                ('expiry_date', models.DateField()),
                ('chain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coupons', to='chain.Chain')),
            ],
            options={
                'ordering': ('expiry_date',),
            },
        ),
    ]
