# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-04 15:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coupon',
            old_name='coupon_code',
            new_name='coupon_name',
        ),
    ]
