# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0002_auto_20170704_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='coupon',
            name='unique_code',
        ),
    ]
