# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 14:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20170707_1047'),
        ('coupon', '0003_remove_coupon_unique_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='CouponCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(blank=True, max_length=7)),
                ('sms', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='code', to='sms.SMS')),
            ],
        ),
    ]
