# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-09 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0004_couponcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='couponcode',
            name='code',
            field=models.CharField(max_length=7),
        ),
    ]
