# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 14:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('chain', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('number', models.CharField(max_length=10, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('chains', models.ManyToManyField(blank=True, related_name='users', to='chain.Chain')),
            ],
        ),
    ]
