# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-03 07:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_auto_20170702_0726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='chains',
            field=models.ManyToManyField(blank=True, related_name='users', to='chain.Chain'),
        ),
    ]
