# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-21 13:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChainSwitcher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('switcher', models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)])),
                ('chain_len', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(100)])),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='switcher', to='customer.Customer')),
            ],
        ),
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.BigIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('message', models.CharField(max_length=140)),
                ('sender_id', models.CharField(max_length=6)),
                ('route', models.CharField(default=b'P', max_length=1)),
            ],
        ),
    ]
