# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-05 16:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SMS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, validators=[django.core.validators.MaxValueValidator(9999999999)])),
                ('message_body', models.CharField(max_length=140)),
            ],
        ),
    ]
