# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-06 12:48
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0003_auto_20170706_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='chainswitcher',
            name='chain_size',
            field=models.PositiveIntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100)]),
            preserve_default=False,
        ),
    ]
