# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-07 04:58
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sms', '0004_chainswitcher_chain_size'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chainswitcher',
            old_name='chain_size',
            new_name='chain_len',
        ),
        migrations.AlterField(
            model_name='chainswitcher',
            name='switcher',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MaxValueValidator(100)]),
        ),
    ]
