# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-12 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chain',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('chain_code', models.CharField(max_length=6, unique=True)),
                ('email', models.EmailField(max_length=70, unique=True)),
                ('address', models.CharField(max_length=300)),
                ('contact_number', models.CharField(max_length=10)),
                ('number_of_stores', models.IntegerField(default=1)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
