# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-07-22 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chain', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chain',
            name='password',
            field=models.CharField(default='dessic', max_length=30),
            preserve_default=False,
        ),
    ]
